import { NextRequest, NextResponse } from "next/server";
import { completeForTool } from "@/lib/llm/gateway";
import { logger } from "@/lib/logger";

const AI_DETECTOR_URL = process.env.AI_DETECTOR_URL ?? "http://localhost:3002";

interface DesklibSentence {
  sentence: string;
  highlight_sentence_for_ai: boolean;
  classification: string;
  perplexity: number;
}

interface DesklibResponse {
  success: boolean;
  result: {
    sentences: DesklibSentence[];
    summary: {
      ai_percentage: number;
      ai_probability: number;
      assessment: string;
      total_sentences: number;
      total_words: number;
    };
  };
}

async function callDesklibDetector(text: string): Promise<{
  sentences: { sentence: string; highlight_sentence_for_ai: boolean }[];
  ai_percentage: number;
} | null> {
  try {
    const res = await fetch(`${AI_DETECTOR_URL}/detect`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text }),
      signal: AbortSignal.timeout(30_000),
    });

    if (!res.ok) {
      logger.warn(`[ai-detector/check] Desklib service returned ${res.status}`);
      return null;
    }

    const data = (await res.json()) as DesklibResponse;
    if (!data.success || !data.result?.sentences) return null;

    return {
      sentences: data.result.sentences.map((s) => ({
        sentence: s.sentence,
        highlight_sentence_for_ai: s.highlight_sentence_for_ai,
      })),
      ai_percentage: Math.round(data.result.summary.ai_percentage),
    };
  } catch {
    return null;
  }
}

function splitSentences(text: string): string[] {
  return text
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { text } = body;

    if (!text || typeof text !== "string") {
      return NextResponse.json({ error: "text is required" }, { status: 400 });
    }

    // Try desklib local model first
    const desklibResult = await callDesklibDetector(text);
    if (desklibResult) {
      logger.info("[ai-detector/check] using desklib model");
      return NextResponse.json({ result: desklibResult });
    }

    // Gemini fallback
    logger.info("[ai-detector/check] desklib unavailable — using Gemini fallback");
    const sentences = splitSentences(text);
    const sentenceList = sentences.map((s, i) => `${i + 1}. ${s}`).join("\n");

    const prompt = `Analyze whether the following text was written by a human or generated by an AI language model.

Analyze each numbered sentence individually. AI-written sentences typically:
- Use formulaic transition phrases ("Furthermore", "Additionally", "In conclusion", "It is worth noting")
- Have unnaturally uniform length and rhythm
- Make perfectly balanced, hedged claims
- Lack personal voice, specific anecdotes, or concrete detail
- Sound polished in a generic, impersonal way

Human-written sentences typically:
- Vary in length — some short, some long, with incomplete thoughts
- Include specific examples, named people, or concrete details
- Have occasional informality or idiosyncratic phrasing
- Express opinions or uncertainty with conviction
- For academic/technical text: formal does NOT equal AI-generated

Return raw JSON only — no markdown, no code fences:
{
  "sentences": [
    { "sentence": "exact sentence text", "highlight_sentence_for_ai": true|false }
  ],
  "ai_percentage": <integer 0-100>
}

Sentences to classify:
${sentenceList}

Full text context:
${text}`;

    const llmResult = await completeForTool("ai-detector", {
      prompt,
      temperature: 0.1,
      maxTokens: Math.max(800, sentences.length * 60),
      jsonMode: true,
    });

    let result: {
      sentences: { sentence: string; highlight_sentence_for_ai: boolean }[];
      ai_percentage: number;
    };

    try {
      const raw = llmResult.text.trim();
      const jsonStr = raw.startsWith("{")
        ? raw
        : raw.replace(/^```(?:json)?\s*/m, "").replace(/```\s*$/m, "").trim();
      result = JSON.parse(jsonStr);
      if (!Array.isArray(result.sentences) || result.sentences.length === 0) {
        throw new Error("Empty sentences array");
      }
    } catch {
      const aiKeywords = [
        "furthermore", "additionally", "in conclusion",
        "it is worth noting", "it is important to",
        "in summary", "notably", "consequently",
      ];
      const aiCount = sentences.filter((s) =>
        aiKeywords.some((kw) => s.toLowerCase().includes(kw))
      ).length;
      const aiPct = Math.min(
        85,
        Math.round((aiCount / Math.max(sentences.length, 1)) * 60) + 20
      );
      result = {
        sentences: sentences.map((s) => ({
          sentence: s,
          highlight_sentence_for_ai: aiKeywords.some((kw) =>
            s.toLowerCase().includes(kw)
          ),
        })),
        ai_percentage: aiPct,
      };
    }

    return NextResponse.json({ result });
  } catch (err) {
    logger.error("[ai-detector/check] Error", {
      error: err instanceof Error ? err.message : String(err),
    });
    return NextResponse.json(
      { error: "Failed to analyze text" },
      { status: 500 }
    );
  }
}
