import SvgColor from "@/components/common/SvgColor";
import { PATH_ACCOUNT, PATH_TOOLS } from "@/config/route";
import { PenLine, Presentation, Search, Table, Target, Compass, Users, Clapperboard, UserRound, Hash } from "lucide-react";
import { ReactElement } from "react";

const icon = (name: string): ReactElement => (
  <SvgColor
    src={`/navbar/${name}.svg`}
    className="h-full w-full"
  />
);

export const NAV_ICONS = {
  writing_studio: <PenLine className="size-3.5 text-emerald-500 sm:size-4" />,
  paraphrase: icon("paraphrase"),
  humanize: icon("humanize"),
  plagiarism_checker: icon("plagiarism_checker"),
  ai_detector: icon("ai_detector"),
  summarize: icon("summarize"),
  grammar_checker: icon("grammar_checker"),
  translator: icon("translator"),
  agents: icon("agents"),
  user: icon("user"),
  marketing_automation: <Target className="size-3.5 text-green-500 sm:size-4" />,
  slide_generation: <Presentation className="size-3.5 text-green-500 sm:size-4" />,
  sheet_generation: <Table className="size-3.5 text-green-500 sm:size-4" />,
  deep_research: <Search className="size-3.5 text-green-500 sm:size-4" />,
  explore: <Compass className="size-3.5 text-amber-500 sm:size-4" />,
  community: <Users className="size-3.5 text-violet-500 sm:size-4" />,
  animation: <Clapperboard className="size-3.5 text-pink-500 sm:size-4" />,
  second_me: <UserRound className="size-3.5 text-indigo-500 sm:size-4" />,
};

export const NAV_TOOLS = [
  {
    icon: NAV_ICONS.writing_studio,
    titleKey: "tools.writingStudio.title",
    descriptionKey: "tools.writingStudio.shortDescription",
    title: "Writing Studio",
    description: "AI-powered text editor",
    labelKey: "common.new",
    label: "New",
    link: "/writing-studio",
    iconColor: "#10B981",
  },
  {
    icon: NAV_ICONS.paraphrase,
    titleKey: "tools.paraphrase.title",
    descriptionKey: "tools.paraphrase.shortDescription",
    title: "Paraphrase",
    description: "Text transformation",
    label: null,
    labelKey: null,
    link: "/paraphrase",
    iconColor: "#FF595E",
  },
  {
    icon: NAV_ICONS.humanize,
    titleKey: "tools.humanizer.title",
    descriptionKey: "tools.humanizer.shortDescription",
    title: "Humanize GPT",
    description: "Overcome limitations",
    label: null,
    labelKey: null,
    link: "/humanize-gpt",
    iconColor: "#FF595E",
  },
  {
    icon: NAV_ICONS.plagiarism_checker,
    titleKey: "tools.plagiarism.title",
    descriptionKey: "tools.plagiarism.shortDescription",
    title: "Plagiarism Checker",
    description: "Authenticity checker",
    label: null,
    labelKey: null,
    link: "/plagiarism-checker",
    iconColor: "#FF595E",
  },
  {
    icon: NAV_ICONS.ai_detector,
    titleKey: "tools.aiDetector.title",
    descriptionKey: "tools.aiDetector.shortDescription",
    title: "AI Detector",
    description: "Authenticity checker",
    link: "/ai-detector",
    label: null,
    labelKey: null,
    iconColor: "#f29b18",
  },
  {
    icon: NAV_ICONS.grammar_checker,
    titleKey: "tools.grammar.title",
    descriptionKey: "tools.grammar.shortDescription",
    title: "Grammar Fix",
    description: "Error correction",
    label: null,
    labelKey: null,
    link: "/grammar-checker",
    iconColor: "#8AC926",
  },
  {
    icon: NAV_ICONS.summarize,
    titleKey: "tools.summarizer.title",
    descriptionKey: "tools.summarizer.shortDescription",
    title: "Summarize",
    description: "Content rephrasing",
    label: null,
    labelKey: null,
    link: "/summarize",
    iconColor: "#FFAB00",
  },
  {
    icon: NAV_ICONS.translator,
    titleKey: "tools.translator.title",
    descriptionKey: "tools.translator.shortDescription",
    title: "Translator",
    description: "Language converter",
    label: null,
    labelKey: null,
    link: "/translator",
    iconColor: "#A07EFB",
  },
  {
    icon: NAV_ICONS.agents,
    titleKey: "tools.agents.title",
    descriptionKey: "tools.agents.description",
    title: "Agents",
    description: "AI Agents Platform",
    label: null,
    labelKey: null,
    link: "/agents",
    iconColor: "#1976D2",
  },
  {
    icon: NAV_ICONS.marketing_automation,
    titleKey: "tools.marketingAutomation.title",
    descriptionKey: "tools.marketingAutomation.description",
    title: "Marketing Automation",
    description: "Marketing automation tools",
    label: null,
    labelKey: null,
    link: "/agents/chat",
    iconColor: "#1976D2",
  },
  {
    icon: NAV_ICONS.explore,
    titleKey: "tools.explore.title",
    descriptionKey: "tools.explore.description",
    title: "Explore",
    description: "Discover twin publications",
    labelKey: "common.new",
    label: "New",
    link: "/explore",
    iconColor: "#F59E0B",
  },
  {
    icon: NAV_ICONS.community,
    titleKey: "tools.community.title",
    descriptionKey: "tools.community.description",
    title: "Community",
    description: "Live twin-human forums",
    labelKey: "common.new",
    label: "New",
    link: "/community",
    iconColor: "#8B5CF6",
  },
  {
    icon: <Hash className="size-3.5 text-violet-500 sm:size-4" />,
    titleKey: "tools.channels.title",
    descriptionKey: "tools.channels.description",
    title: "Channels",
    description: "STEM domain communities",
    label: null,
    labelKey: null,
    link: "/explore/channels",
    iconColor: "#8B5CF6",
  },
  {
    icon: NAV_ICONS.animation,
    titleKey: "tools.animation.title",
    descriptionKey: "tools.animation.description",
    title: "Animation",
    description: "AI video generation",
    label: null,
    labelKey: null,
    link: "/animation",
    iconColor: "#EC4899",
  },
  {
    icon: NAV_ICONS.second_me,
    titleKey: "tools.twin.title",
    descriptionKey: "tools.twin.description",
    title: "Twin",
    description: "Your unified AI twin",
    labelKey: "common.new",
    label: "New",
    link: "/twin",
    iconColor: "#6366F1",
  },
];

export const NAV_ITEMS = [
  {
    subheader: "account",
    roles: ["user", "admin"],
    items: [
      {
        titleKey: "account.yourAccount",
        title: "Your account",
        path: PATH_ACCOUNT.settings.root,
        icon: NAV_ICONS.user,
        iconColor: "#3498DB",
      },
    ],
  },
];
