export const aidetectorFaq = [
  {
    question: "What is Shothik AI's AI Detector?",
    answer:
      "Our AI Detector is a sophisticated tool designed to identify AI-generated content with high accuracy. It uses advanced algorithms to analyze text and determine whether it was likely written by a human or generated by AI tools like ChatGPT, GPT-4, Claude, or other language models.",
  },
  {
    question: "How accurate is the AI Detector?",
    answer: (
      <>
        <p>
          Our AI Detector offers industry-leading accuracy with the following
          features:
        </p>
        <ul style={{ marginLeft: "1.5em" }}>
          <li>95%+ accuracy rate in identifying AI-generated content</li>
          <li>Advanced pattern recognition algorithms</li>
          <li>Continuous learning and updates to detect latest AI models</li>
        </ul>
      </>
    ),
  },
  {
    question: "What types of AI-generated content can it detect?",
    answer: (
      <>
        <p>
          Our AI Detector can identify content generated by various AI sources:
        </p>
        <ul style={{ marginLeft: "1.5em" }}>
          <li>ChatGPT (All versions)</li>
          <li>GPT-4</li>
          <li>Claude</li>
          <li>Bard</li>
          <li>Hix</li>
          <li>StealthWriter</li>
          <li>LLaMA</li>
          <li>Google AI</li>
          <li>Microsoft Azure AI</li>
        </ul>
        <p>
          It works effectively across different content types including essays,
          articles, reports, and creative writing.
        </p>
      </>
    ),
  },
  {
    question: "How does the AI Detector work?",
    answer: (
      <>
        <p>Our AI Detector analyzes text using multiple factors:</p>
        <ul style={{ marginLeft: "1.5em" }}>
          <li>Writing patterns and consistency</li>
          <li>Language structure and complexity</li>
          <li>Vocabulary usage and variation</li>
          <li>Contextual coherence</li>
          <li>Statistical patterns typical of AI generation</li>
          <li>Semantic analysis</li>
        </ul>
        <p>
          It combines these factors to provide a comprehensive assessment of
          whether the text is AI-generated.
        </p>
      </>
    ),
  },
  {
    question: "What information does the detection report provide?",
    answer: (
      <>
        <p>Each detection report includes:</p>
        <ul style={{ marginLeft: "1.5em" }}>
          <li>
            <strong>AI Probability Score:</strong> Percentage likelihood of AI
            generation
          </li>
          <li>
            <strong>Confidence Level:</strong> Reliability of the detection
            result
          </li>
          <li>
            <strong>Detailed Analysis:</strong> Breakdown of detected patterns
          </li>
          <li>
            <strong>Highlighted Sections:</strong> Parts of text most likely to
            be AI-generated
          </li>
          <li>
            <strong>Recommendations:</strong> Suggestions for content
            improvement
          </li>
        </ul>
      </>
    ),
  },
];
