import { NextRequest, NextResponse } from "next/server";
import { ConvexHttpClient } from "convex/browser";
import { api } from "@/convex/_generated/api";
import { getAuthToken } from "@/lib/auth";
import { logger } from "@/lib/logger";

const convex = new ConvexHttpClient(process.env.NEXT_PUBLIC_CONVEX_URL!);

const CATEGORY_TO_THEMA: Record<string, string> = {
  "fiction_literary": "FBA",
  "fiction_scifi": "FK",
  "fiction_fantasy": "FM",
  "fiction_romance": "FRD",
  "fiction_thriller": "FH",
  "fiction_mystery": "FF",
  "fiction_horror": "FQ",
  "fiction_historical": "FV",
  "nonfiction_science": "P",
  "nonfiction_business": "KJ",
  "nonfiction_selfhelp": "VS",
  "nonfiction_biography": "DN",
  "nonfiction_history": "NH",
  "nonfiction_education": "JN",
  "nonfiction_health": "VF",
  "academic_stem": "PD",
  "academic_engineering": "TBC",
  "academic_medicine": "MBD",
  "academic_social": "JH",
  "academic_humanities": "QD",
  "academic_computer": "UB",
  "academic_math": "PB",
  "poetry": "DC",
  "children": "YB",
  "young_adult": "YF",
  "comics": "X",
};

function escapeXml(str: string): string {
  return (str || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export function buildOnix3(book: Record<string, unknown>): string {
  const now = new Date();
  const datestamp = now.toISOString().slice(0, 10).replace(/-/g, "");
  const publishingYear = now.getFullYear().toString();

  const title = escapeXml((book.title as string) || "Untitled");
  const subtitle = book.subtitle
    ? `\n        <TitleElement>\n          <TitleElementLevel>02</TitleElementLevel>\n          <TitleText>${escapeXml(book.subtitle as string)}</TitleText>\n        </TitleElement>`
    : "";
  const description = escapeXml((book.description as string) || "");
  const language = ((book.language as string) || "en").toLowerCase().slice(0, 2);
  const listPrice = parseFloat((book.listPrice as string) || "9.99").toFixed(2);
  const currency = ((book.currency as string) || "USD").toUpperCase();
  const category = (book.category as string) || "";
  const themaCode = CATEGORY_TO_THEMA[category] || "G";
  const keywords = ((book.keywords as string[]) || []).join("; ");
  const isbn = (book.isbn as string) || "";

  const authorName = escapeXml((book.agreementName as string) || "");
  const authorParts = authorName.split(/\s+/);
  const authorLastName = authorParts.length > 1 ? authorParts[authorParts.length - 1] : authorName;
  const authorFirstName = authorParts.length > 1 ? authorParts.slice(0, -1).join(" ") : "";

  const isbnBlock = isbn
    ? `\n    <ProductIdentifier>\n      <ProductIDType>15</ProductIDType>\n      <IDValue>${escapeXml(isbn)}</IDValue>\n    </ProductIdentifier>`
    : "";

  const keywordsBlock = keywords
    ? `\n      <Subject>\n        <SubjectSchemeIdentifier>20</SubjectSchemeIdentifier>\n        <SubjectHeadingText>${escapeXml(keywords)}</SubjectHeadingText>\n      </Subject>`
    : "";

  const firstNameEl = authorFirstName
    ? `\n        <NamesBeforeKey>${escapeXml(authorFirstName)}</NamesBeforeKey>`
    : "";

  return `<?xml version="1.0" encoding="UTF-8"?>
<ONIXMessage release="3.0"
  xmlns="http://ns.editeur.org/onix/3.0/reference"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <Header>
    <Sender>
      <SenderName>Shothik Publishing</SenderName>
      <ContactName>Shothik AI Platform</ContactName>
      <EmailAddress>publishing@shothik.ai</EmailAddress>
    </Sender>
    <SentDateTime>${datestamp}</SentDateTime>
    <MessageNote>Generated by Shothik AI Publishing Platform</MessageNote>
  </Header>

  <Product>
    <RecordReference>${escapeXml((book._id as string) || "shothik-" + Date.now())}</RecordReference>
    <NotificationType>03</NotificationType>

    <ProductIdentifier>
      <ProductIDType>01</ProductIDType>
      <IDValue>${escapeXml((book._id as string) || "")}</IDValue>
    </ProductIdentifier>${isbnBlock}

    <DescriptiveDetail>
      <ProductComposition>00</ProductComposition>
      <ProductForm>ED</ProductForm>
      <ProductFormDetail>E101</ProductFormDetail>

      <TitleDetail>
        <TitleType>01</TitleType>
        <TitleElement>
          <TitleElementLevel>01</TitleElementLevel>
          <TitleText>${title}</TitleText>
        </TitleElement>${subtitle}
      </TitleDetail>

      <Contributor>
        <SequenceNumber>1</SequenceNumber>
        <ContributorRole>A01</ContributorRole>${firstNameEl}
        <KeyNames>${escapeXml(authorLastName || authorName)}</KeyNames>
        <PersonName>${escapeXml(authorName)}</PersonName>
      </Contributor>

      <Language>
        <LanguageRole>01</LanguageRole>
        <LanguageCode>${language}</LanguageCode>
      </Language>

      <Subject>
        <SubjectSchemeIdentifier>10</SubjectSchemeIdentifier>
        <SubjectCode>${escapeXml(category)}</SubjectCode>
      </Subject>
      <Subject>
        <SubjectSchemeIdentifier>93</SubjectSchemeIdentifier>
        <SubjectCode>${escapeXml(themaCode)}</SubjectCode>
      </Subject>${keywordsBlock}
    </DescriptiveDetail>

    <CollateralDetail>
      <TextContent>
        <TextType>03</TextType>
        <ContentAudience>00</ContentAudience>
        <Text textformat="06">${description}</Text>
      </TextContent>
    </CollateralDetail>

    <PublishingDetail>
      <Imprint>
        <ImprintName>Shothik Publishing</ImprintName>
      </Imprint>
      <Publisher>
        <PublishingRole>01</PublishingRole>
        <PublisherName>Shothik AI</PublisherName>
      </Publisher>
      <PublishingStatus>04</PublishingStatus>
      <PublishingDate>
        <PublishingDateRole>01</PublishingDateRole>
        <Date>${publishingYear}</Date>
      </PublishingDate>
    </PublishingDetail>

    <ProductSupply>
      <Market>
        <Territory>
          <RegionsIncluded>WORLD</RegionsIncluded>
        </Territory>
      </Market>
      <SupplyDetail>
        <Supplier>
          <SupplierRole>09</SupplierRole>
          <SupplierName>Shothik AI</SupplierName>
        </Supplier>
        <ProductAvailability>20</ProductAvailability>
        <Price>
          <PriceType>02</PriceType>
          <PriceAmount>${listPrice}</PriceAmount>
          <CurrencyCode>${currency}</CurrencyCode>
          <Territory>
            <RegionsIncluded>WORLD</RegionsIncluded>
          </Territory>
        </Price>
      </SupplyDetail>
    </ProductSupply>
  </Product>

</ONIXMessage>`;
}

export async function POST(req: NextRequest) {
  try {
    const token = getAuthToken(req);
    if (!token) {
      return NextResponse.json({ error: "Authentication required" }, { status: 401 });
    }

    const { bookId } = await req.json();
    if (!bookId) {
      return NextResponse.json({ error: "bookId is required" }, { status: 400 });
    }

    const book = await convex.query(api.books.get, { id: bookId });
    if (!book) {
      return NextResponse.json({ error: "Book not found" }, { status: 404 });
    }

    const onixXml = buildOnix3(book as Record<string, unknown>);

    return new NextResponse(onixXml, {
      status: 200,
      headers: {
        "Content-Type": "application/xml; charset=utf-8",
        "Content-Disposition": `attachment; filename="onix_${bookId}.xml"`,
      },
    });
  } catch (error) {
    logger.error("ONIX generation error:", error);
    return NextResponse.json({ error: "Failed to generate ONIX metadata" }, { status: 500 });
  }
}

export async function GET(req: NextRequest) {
  try {
    const token = getAuthToken(req);
    if (!token) {
      return NextResponse.json({ error: "Authentication required" }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const bookId = searchParams.get("bookId");

    if (!bookId) {
      return NextResponse.json({ error: "bookId is required" }, { status: 400 });
    }

    convex.setAuth(token);
    const book = await convex.query(api.books.get, { id: bookId as any });
    if (!book) {
      return NextResponse.json({ error: "Book not found" }, { status: 404 });
    }

    if (book.status !== "approved" && book.status !== "published") {
      return NextResponse.json({ error: "Book is not published" }, { status: 403 });
    }

    const onixXml = buildOnix3(book as Record<string, unknown>);

    return new NextResponse(onixXml, {
      status: 200,
      headers: {
        "Content-Type": "application/xml; charset=utf-8",
        "Content-Disposition": `attachment; filename="onix_${bookId}.xml"`,
      },
    });
  } catch (error) {
    logger.error("ONIX GET error:", error);
    return NextResponse.json({ error: "Failed to generate ONIX metadata" }, { status: 500 });
  }
}
