import { NextRequest, NextResponse } from "next/server";
import { aiDetectionSchema } from "@/lib/validation";
import { completeForTool } from "@/lib/llm/gateway";
import { logger } from "@/lib/logger";
import { enforceUsageLimit, recordToolUsage } from "@/lib/usage-enforcement";
import { checkTieredToolRateLimit } from "@/lib/tool-rate-limiter";

const AI_DETECTOR_URL = process.env.AI_DETECTOR_URL ?? "http://localhost:3002";

interface DetectionResult {
  score: number;
  isAIGenerated: boolean;
  confidence: number;
  analysis: string;
  indicators: Record<string, string | number | boolean>;
}

interface DesklibResponse {
  success: boolean;
  result: {
    sentences: { sentence: string; highlight_sentence_for_ai: boolean; classification: string; perplexity: number }[];
    summary: {
      ai_percentage: number;
      ai_probability: number;
      assessment: string;
      total_sentences: number;
      total_words: number;
    };
  };
}

async function callDesklibDetector(text: string): Promise<DetectionResult | null> {
  try {
    const res = await fetch(`${AI_DETECTOR_URL}/detect`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text }),
      signal: AbortSignal.timeout(30_000),
    });

    if (!res.ok) return null;

    const data = (await res.json()) as DesklibResponse;
    if (!data.success || !data.result?.summary) return null;

    const { ai_percentage, ai_probability, assessment } = data.result.summary;
    const score = Math.round(ai_percentage);
    const isAIGenerated = score >= 60;

    const aiSentences = data.result.sentences
      .filter((s) => s.highlight_sentence_for_ai)
      .slice(0, 2)
      .map((s) => `"${s.sentence.slice(0, 60)}..."`)
      .join("; ");

    const analysis = isAIGenerated
      ? `Text scores ${score}% AI-generated (probability: ${(ai_probability * 100).toFixed(1)}%). ${aiSentences ? `AI-flagged sentences include: ${aiSentences}` : assessment}`
      : `Text scores ${score}% AI-generated (probability: ${(ai_probability * 100).toFixed(1)}%). ${assessment}`;

    const highPerplexitySentences = data.result.sentences.filter((s) => s.perplexity < 50).length;
    const totalSentences = data.result.sentences.length;

    return {
      score,
      isAIGenerated,
      confidence: Math.min(95, 60 + Math.abs(score - 50)),
      analysis,
      indicators: {
        uniformSentenceStructure: score > 70 ? "high" : score > 40 ? "medium" : "low",
        formalTransitions: score > 60 ? "high" : "low",
        repetitivePatterns: score > 70 ? "high" : "medium",
        lacksPersonalVoice: isAIGenerated,
        overlyPrecise: highPerplexitySentences > totalSentences * 0.5,
      },
    };
  } catch {
    return null;
  }
}

export async function POST(req: NextRequest) {
  try {
    const usageCheck = await enforceUsageLimit(req, "ai-detector");
    if (!usageCheck.allowed && usageCheck.response) {
      return usageCheck.response;
    }

    if (usageCheck.userId) {
      const rateCheck = await checkTieredToolRateLimit(usageCheck.userId, usageCheck.tier ?? "free", "ai-detector");
      if (!rateCheck.allowed && rateCheck.response) {
        return rateCheck.response;
      }
    }

    const body = await req.json();
    const parsed = aiDetectionSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: parsed.error.flatten() }, { status: 422 });
    }
    const { text } = parsed.data;

    if (text.length > 10000) {
      return NextResponse.json(
        { error: "Text too long (max 10,000 characters)" },
        { status: 400 }
      );
    }

    // Try desklib local model first
    const desklibResult = await callDesklibDetector(text);
    if (desklibResult) {
      logger.info("[ai-detector/tools] using desklib model");
      if (usageCheck.userId) {
        await recordToolUsage(usageCheck.userId, "ai-detector");
      }
      return NextResponse.json({ success: true, text, ...desklibResult });
    }

    // Gemini fallback
    logger.info("[ai-detector/tools] desklib unavailable — using Gemini fallback");

    let result: DetectionResult;
    try {
      const prompt = `Analyze whether the following text was written by a human or generated by an AI language model.

Consider the full context: academic papers, formal reports, and legal documents are written formally by humans — do not penalise formal writing. Look instead for AI-specific patterns.

Return raw JSON only — no markdown, no code fences:
{
  "score": <integer 0-100, where 0=definitely human, 100=definitely AI>,
  "confidence": <integer 0-100, your confidence in the score>,
  "analysis": "<2-3 sentences citing the specific signals you found — quote phrases from the text>",
  "indicators": {
    "uniformSentenceStructure": "<low|medium|high>",
    "formalTransitions": "<low|medium|high>",
    "repetitivePatterns": "<low|medium|high>",
    "lacksPersonalVoice": <true|false>,
    "overlyPrecise": <true|false>
  }
}

Text to analyze:
${text}`;

      const llmResult = await completeForTool("ai-detector", {
        prompt,
        temperature: 0.1,
        maxTokens: 500,
        jsonMode: true,
      });

      const raw = llmResult.text.trim();
      const jsonStr = raw.startsWith("{")
        ? raw
        : raw.replace(/^```(?:json)?\s*/m, "").replace(/```\s*$/m, "").trim();
      const parsedResult = JSON.parse(jsonStr) as Omit<DetectionResult, "isAIGenerated">;
      result = { ...parsedResult, isAIGenerated: parsedResult.score >= 60 };
    } catch (err) {
      logger.warn("[ai-detector/tools] Gemini parse failed, using heuristic fallback", {
        error: err instanceof Error ? err.message : String(err),
      });
      result = heuristicDetection(text);
    }

    if (usageCheck.userId) {
      await recordToolUsage(usageCheck.userId, "ai-detector");
    }

    return NextResponse.json({ success: true, text, ...result });
  } catch (error) {
    logger.error("[ai-detector/tools] error", {
      error: error instanceof Error ? error.message : String(error),
    });
    return NextResponse.json({ error: "Failed to analyze text" }, { status: 500 });
  }
}

function heuristicDetection(text: string): DetectionResult {
  const repetitivePatterns = (text.match(/\b(in addition|furthermore|moreover)\b/gi) || []).length;
  const sentences = text.split(/[.!?]+/).filter((s) => s.trim());
  const avgSentenceLength = sentences.reduce((sum, s) => sum + s.length, 0) / Math.max(sentences.length, 1);
  const formalTransitions = (text.match(/\b(therefore|thus|consequently|hence)\b/gi) || []).length;
  const lacksContractions = !text.match(/\b(don't|can't|won't|isn't|aren't|I've|I'm)\b/i);

  let score = 40;
  if (repetitivePatterns > 2) score += 15;
  if (avgSentenceLength > 100) score += 10;
  if (formalTransitions > 2) score += 10;
  if (lacksContractions) score += 10;
  score = Math.min(100, score);

  return {
    score,
    isAIGenerated: score >= 60,
    confidence: 45,
    analysis: score >= 60
      ? "Text shows patterns consistent with AI generation: formal transitions, uniform sentence structure."
      : "Text appears to be human-written based on available linguistic signals.",
    indicators: {
      uniformSentenceStructure: repetitivePatterns > 1 ? "high" : "low",
      formalTransitions: formalTransitions > 2 ? "high" : "low",
      repetitivePatterns: repetitivePatterns > 2 ? "high" : "low",
      lacksPersonalVoice: lacksContractions,
      overlyPrecise: false,
    },
  };
}
