export const team = [
  // Leadership & Executive
  {
    order: 1,
    id: "1",
    name: "Ahsan Habib",
    designation: "Founder & CEO",
    image: "/team/habib.jpg",
    social: [
      "https://www.linkedin.com/in/ahsan577/",
      "https://www.facebook.com/ahsan.habib577",
      "#",
      "#",
      "#",
      "#",
    ],
  },
  {
    order: 2,
    id: "2",
    name: "Alamgir Ahamed",
    designation: "Chief Technology Officer",
    image: "/team/alamgir.jpg",
    social: [
      "https://www.linkedin.com/in/alamgir-ahamed-7b4b1b1b0",
      "https://www.facebook.com/alamgir.ahamed.dev",
      "#",
      "#",
      "#",
      "#",
    ],
  },
  {
    order: 3,
    id: "3",
    name: "Sudip Majumder",
    designation: "Advisor",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 4,
    id: "4",
    name: "Salvia Benazir",
    designation: "Director & Talent acquisition Specialist",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },

  // Engineering Team - Fullstack Developers
  {
    order: 5,
    id: "5",
    name: "Md. Iqbal Hossen",
    designation: "Fullstack Developer",
    image: "/team/iqbal.jpg",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 6,
    id: "6",
    name: "Kazi Riad Uddin",
    designation: "Fullstack Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 7,
    id: "7",
    name: "Mehedi Hasan",
    designation: "Fullstack Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 8,
    id: "8",
    name: "Joaria Manjur",
    designation: "Fullstack Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 9,
    id: "9",
    name: "Israt Jahan Sumona",
    designation: "Fullstack Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 10,
    id: "10",
    name: "Noor Ferdousi Mitu",
    designation: "Fullstack Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 11,
    id: "11",
    name: "Rahmat Ullah",
    designation: "Fullstack Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 28,
    id: "28",
    name: "Jobayer Ahmed",
    designation: "Fullstack Developer",
    image: "/team/jobayer.jpg",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 12,
    id: "12",
    name: "Foysal Ahmed",
    designation: "Fullstack Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 13,
    id: "13",
    name: "Shaikot Kundu Akash",
    designation: "Fullstack Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },

  // Engineering Team - Frontend Developers
  {
    order: 14,
    id: "14",
    name: "Topon Mohonto",
    designation: "Frontend Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 15,
    id: "15",
    name: "Surjya Bhowmick",
    designation: "Frontend Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 16,
    id: "16",
    name: "Nahidul Islam",
    designation: "Frontend Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 17,
    id: "17",
    name: "Mohosina",
    designation: "Frontend Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 18,
    id: "18",
    name: "Yamin",
    designation: "Frontend Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 19,
    id: "19",
    name: "Rashaduzamman Rian",
    designation: "Frontend Developer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },

  // Engineering Team - AI Engineers
  {
    order: 20,
    id: "20",
    name: "Nazmius Sakib",
    designation: "AI Engineer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 21,
    id: "21",
    name: "Jakir Hossain",
    designation: "AI Engineer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },

  // Design Team
  {
    order: 22,
    id: "22",
    name: "MST Atika",
    designation: "UI/UX Designer",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },

  // Operations & Support
  {
    order: 23,
    id: "23",
    name: "Arpan Das",
    designation: "Executive Assistant",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },

  // Legal & Compliance Team
  {
    order: 24,
    id: "24",
    name: "Barrister Riazuddin",
    designation: "Legal Advisor",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 25,
    id: "25",
    name: "Barrister Sm Saad",
    designation: "Legal Consultant",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 26,
    id: "26",
    name: "Barrister Shanjid Siddique",
    designation: "Legal Advisor",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
  {
    order: 27,
    id: "27",
    name: "Advocate Obayed Enam",
    designation: "Legal Advisor",
    image: "/team/placeholder.png",
    social: ["#", "#", "#", "#", "#"],
  },
];
