export const toolsCta = {
  paraphrase: {
    title: "Transform Your Writing",
    heading: "Elevate Your Content with Smart Paraphrasing",
    description:
      "Transform your text instantly with AI-powered paraphrasing. Get unique, engaging content while maintaining your original message.",
    image: {
      light: "/cta/cta_light.png",
      dark: "/cta/cta_dark.png",
    },
    buttonText: "Explore it Now",
    buttonLink: "/pricing",
  },
  humanize: {
    title: "Humanize Your AI Content",
    heading: (
      <>
        Make AI Content Sound Human with{" "}
        <span className="text-primary">Panda</span> and{" "}
        <span className="text-primary">Raven</span> Models
      </>
    ),
    description: (
      <p>
        Explore the power of Humanize GPT - a game-changing AI tool that
        converts AI-generated text into natural, human-like content that
        resonates with your audience.
      </p>
    ),
    image: {
      light: "/cta/humanize_dark.png",
      dark: "/cta/humanize_light.png",
    },
    buttonText: "Explore it Now",
    buttonLink: "/pricing",
  },
  aidetector: {
    title: "AI Content Detection",
    heading: "Detect AI-Generated Content",
    description: (
      <p>
        AI Detector is a sophisticated tool designed to identify AI-generated
        content with high accuracy. It uses advanced algorithms to analyze
        text and determine whether it was likely written by a human or
        generated by AI tools like ChatGPT, GPT-4, Claude, or other language
        models.
      </p>
    ),
    image: {
      light: "/cta/aidetector_light.png",
      dark: "/cta/aidetector_dark.png",
    },
    buttonText: "Explore it Now",
    buttonLink: "/pricing",
  },
  grammar: {
    title: "Perfect Your Grammar",
    heading: "Advanced Grammar Checking",
    description: (
      <p>
        Grammar Fix is an advanced writing tool that helps you identify and
        correct grammatical errors, spelling mistakes, punctuation issues, and
        style improvements in your text. It uses AI-powered algorithms to
        provide comprehensive writing suggestions while maintaining your
        original message and tone.
      </p>
    ),
    image: {
      light: "/cta/grammar_light.png",
      dark: "/cta/grammar_dark.png",
    },
    buttonText: "Explore it Now",
    buttonLink: "/pricing",
  },
  translator: {
    title: "Translate Anything",
    heading: "Professional Translation Service",
    description: (
      <p>
        Translator is a powerful AI-driven language translation tool that
        provides accurate, context-aware translations across multiple
        languages. It understands nuances, idioms, and cultural context to
        deliver natural-sounding translations while maintaining the original
        meaning.
      </p>
    ),
    image: {
      light: "/cta/translate_light.png",
      dark: "/cta/translate_dark.png",
    },
    buttonText: "Explore it Now",
    buttonLink: "/pricing",
  },
  summarize: {
    title: "Smart Summarization",
    heading: "Summarize Any Text",
    description: (
      <p>
        Summarize feature is an advanced AI-powered tool that condenses long
        texts into clear, concise summaries while retaining the most important
        information. It helps you quickly understand key points from articles,
        documents, research papers, and other content without losing essential
        context.
      </p>
    ),
    image: {
      light: "/cta/summarize_light.png",
      dark: "/cta/summarize_dark.png",
    },
    buttonText: "Explore it Now",
    buttonLink: "/pricing",
  },
};
